### PR TITLE
dotfiles: update

### PR DESCRIPTION
**Pull request by djchittoor**
- add **Artix Linux** to _supported distros_

- force **Brave** to _$ws2_

- add **quick keybinds** and **functions** for configuring window gaps

- get rid of the **system beep**

### CODE REVIEW

**Review by merothh — CHANGES_REQUESTED** [review]
might as well sort those $ws2 entries

**Review by merothh — COMMENTED** [review]
Sort the distros

**Review by merothh — APPROVED** [review]
LGTM

**Review by merothh — COMMENTED** [review]
I'll need to try this out. Maybe a separate PR ?

**Comment by djchittoor** [comment]
Updated as per owner's review.

-  Sorted _supported distros_ **alphabetically**
-  Sorted _$ws2 classes_ **alphabetically**
-  Drop _resize window gaps_ function as per owner's review for it be included in **another separate PR**

**Pull request merged**
